### ISSUE TITLE
Generated python stub do not support optional properties in complex types

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/go-raml#274]
NicLink in the following example has an optional macaddress field. But when creating the object via python it complains that macaddress is not added. Also specifying ```None``` does not help.

```python
Traceback (most recent call last):
  File "deployvms.py", line 77, in <module>
    create()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "deployvms.py", line 61, in create
    nic = NicLink.create(type=EnumNicLinkType.default, id=0)
TypeError: create() missing 1 required positional argument: 'macaddress'
```

**Comment by iwanbk** [comment]
raml file and code usage example will be very helpful to address this issue
