### ISSUE TITLE
Error generating zerotier client

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/go-raml#309]
Raml file used : https://github.com/zero-os/zerotier_client/blob/master/api.raml

Error :
```
go-raml client -l python --ramlfile api.raml --dir zerotier 
panic: inline item's properties expect properties in type:map[string]interface{}

goroutine 1 [running]:
github.com/Jumpscale/go-raml/raml.(*Type).createTypeFromPropItems(0xc42015c928, 0xc420180260, 0x11, 0xc42006cb00)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/raml/types.go:684 +0x601
github.com/Jumpscale/go-raml/raml.(*Type).postProcess(0xc42015c928, 0xc42016ee30, 0xd, 0xc42006cb00, 0x0, 0x0)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/raml/types.go:649 +0x193
github.com/Jumpscale/go-raml/raml.(*APIDefinition).PostProcess(0xc42006cb00, 0x864ddc, 0x1, 0x7ffc026e19f2, 0x8, 0x0, 0x0)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/raml/apidefinition.go:133 +0x87a
github.com/Jumpscale/go-raml/raml.ParseReadFile(0x7ffc026e19f2, 0x0, 0x7ffc026e19f2, 0x8, 0xa2ffc0, 0xc42006cb00, 0x410ab8, 0x100, 0x857de0, 0x1, ...)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/raml/parser.go:140 +0x637
github.com/Jumpscale/go-raml/raml.ParseFile(0x7ffc026e19f2, 0x8, 0xa2ffc0, 0xc42006cb00, 0x78fecc, 0xc4201260a0)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/raml/parser.go:68 +0x7c
github.com/Jumpscale/go-raml/commands.(*ClientCommand).Execute(0xbf8da0, 0xc4200b78c0, 0x865536)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/commands/client.go:34 +0x159
main.main.func3(0xc4200b78c0)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/main.go:166 +0x2d
github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli.Command.Run(0x865e98, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8753d5, 0x28, 0x0, ...)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli/command.go:137 +0x88a
github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200b7680, 0xc420084080, 0x8, 0x8, 0x0, 0x0)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli/app.go:176 +0x8e8
main.main()
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/main.go:256 +0x1839
```

**Comment by iwanbk** [comment]
@zaibon 
this form is not supported yet
```
type: array
        items:
          type: NetworkRule
```
for temporary solution, you can change it to 
```
type: array
        items: NetworkRule
```
Tested to work with this modification
```diff
--- /Users/ibk/tmp/api.raml	2017-06-17 06:56:09.000000000 +0700
+++ ./api.raml	2017-06-17 06:58:20.000000000 +0700
@@ -86,8 +86,7 @@
             body:
               application/json:
                 type: array
-                items:
-                  type: NetworkMember
+                items: NetworkMember
             description: Array of incomplete / preview NetworkMember object
           '403':
             body:
@@ -116,8 +115,7 @@
         body:
           application/json:
             type: array
-            items:
-              type: Network
+            items: Network
         description: Array of incomplete / preview Network objects
       '403':
         body:
@@ -180,8 +178,7 @@
         body:
           application/json:
             type: array
-            items:
-              type: User
+            items: User
         description: Array of incomplete / preview user records
       '403':
         body:
@@ -366,9 +363,8 @@
         required: false
       ipAssignments:
         type: array
-        items:
-          type: string
-          description: 'IP/netmask bits (e.g. ''10.0.0.1/24'' or ''dead:beef:0000:0000:0000:0000:0000:0001/88'')'
+        items: string
+        description: 'IP/netmask bits (e.g. ''10.0.0.1/24'' or ''dead:beef:0000:0000:0000:0000:0000:0001/88'')'
         required: false
       memberRevision:
         type: integer
@@ -407,13 +403,11 @@
         required: false
       rules:
         type: array
-        items:
-          type: NetworkRule
+        items: NetworkRule
         required: false
       relays:
         type: array
-        items:
-          type: NetworkRelay
+        items: NetworkRelay
         required: false
       private:
         type: boolean
@@ -443,14 +437,12 @@
         required: false
       ipLocalRoutes:
         type: array
-        items:
-          type: string
-          description: IP/netmask bits e.g. '10.0.0.0/24'
+        items: string
+        description: IP/netmask bits e.g. '10.0.0.0/24'
         required: false
       ipAssignmentPools:
         type: array
-        items:
-          type: NetworkIpAssignmentPool
+        items: NetworkIpAssignmentPool
         required: false
       controllerInstanceId:
         type: string
```

**Comment by zaibon** [comment]
Good catch, thank you.
