### ISSUE TITLE
Panic when using /: endpoint

### ISSUE THREAD

**Issue by maxux** [Jumpscale/go-raml#324]
This simple piece of RAML code makes `go-raml` panic:
```
#%RAML 1.0
title: Panic Demo
version: 1.0
mediaType: application/json

/repositories:
  /:
    get:
      description: List all repositories (users) found
```

Adding a single letter after the `/` (eg: `/a`) works correctly.

Here is panic backtrace:
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/Jumpscale/go-raml/codegen/python._snakeCaseResourceURI(0xc4201520d0, 0x0, 0x0, 0xc420018f00, 0xc42009e300)
	/opt/code/go/src/github.com/Jumpscale/go-raml/codegen/python/method.go:168 +0x2ec
github.com/Jumpscale/go-raml/codegen/python.snakeCaseResourceURI(0xc4201520d0, 0xe, 0xc420137b18)
	/opt/code/go/src/github.com/Jumpscale/go-raml/codegen/python/method.go:151 +0x3d
github.com/Jumpscale/go-raml/codegen/python.(*clientMethod).setup(0xc420138608)
	/opt/code/go/src/github.com/Jumpscale/go-raml/codegen/python/method.go:145 +0x6d3
github.com/Jumpscale/go-raml/codegen/python.newClientMethod(0xc4201520d0, 0xc420067f80, 0xc4200a4600, 0x868aae, 0x3, 0x4da61b, 0xc420138810, 0x4db390, 0x75)
	/opt/code/go/src/github.com/Jumpscale/go-raml/codegen/python/method.go:107 +0x22e
github.com/Jumpscale/go-raml/codegen/resource.(*Resource).addMethod(0xc420067f80, 0xc4201520d0, 0xc4200a4600, 0x868aae, 0x3, 0x882700, 0x8826f8)
	/opt/code/go/src/github.com/Jumpscale/go-raml/codegen/resource/resources.go:55 +0x1ea
github.com/Jumpscale/go-raml/codegen/resource.(*Resource).GenerateMethods(0xc420067f80, 0xc4201520d0, 0x8697ab, 0x6, 0x882700, 0x8826f8)
	/opt/code/go/src/github.com/Jumpscale/go-raml/codegen/resource/resources.go:66 +0x85
github.com/Jumpscale/go-raml/codegen/resource.(*Resource).GenerateMethods(0xc420067f80, 0xc4201524e0, 0x8697ab, 0x6, 0x882700, 0x8826f8)
	/opt/code/go/src/github.com/Jumpscale/go-raml/codegen/resource/resources.go:74 +0x2d4
github.com/Jumpscale/go-raml/codegen/python.NewClient(0xc4200a4500, 0x86a227, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/code/go/src/github.com/Jumpscale/go-raml/codegen/python/client.go:41 +0x27e
github.com/Jumpscale/go-raml/codegen.GenerateClient(0xc4200a4500, 0x7fff370bf140, 0x6, 0x7fff370bf16a, 0x7, 0x7fff370bf133, 0x6, 0x0, 0x0, 0x86a227, ...)
	/opt/code/go/src/github.com/Jumpscale/go-raml/codegen/client.go:22 +0xe9
github.com/Jumpscale/go-raml/commands.(*ClientCommand).Execute(0xc36760, 0xc4200a78c0, 0x868eac)
	/opt/code/go/src/github.com/Jumpscale/go-raml/commands/client.go:38 +0x210
main.main.func3(0xc4200a78c0)
	/opt/code/go/src/github.com/Jumpscale/go-raml/main.go:166 +0x2d
github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli.Command.Run(0x8696a3, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x878011, 0x28, 0x0, ...)
	/opt/code/go/src/github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli/command.go:137 +0x7f2
github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200a7680, 0xc4200100a0, 0xa, 0xa, 0x0, 0x0)
	/opt/code/go/src/github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli/app.go:176 +0x8c1
main.main()
	/opt/code/go/src/github.com/Jumpscale/go-raml/main.go:256 +0x1792
```

**Comment by iwanbk** [comment]
OK, this needs to be fixed.

On the other hand, is `/:` a valid RAML?

**Comment by maxux** [comment]
Actually, I'm not sur this is a valid endpoint but at least `raml2html` accepts it and shows it.
I guess the panic should be fixed anyway.

**Comment by iwanbk** [comment]
> Actually, I'm not sur this is a valid endpoint but at least raml2html accepts it and shows it.

OK, might be valid
