### ISSUE TITLE
inconsistent schema names generated and used in the generated python files.

### ISSUE THREAD

**Issue by xmonader** [Jumpscale/go-raml#399]
### Versions
* RAML code generation toolset version 0.1-Dev
* COMMIT: a5aed17caa97fd822abd86c59abf4465b07172a6

### RAML specs
API specs are available here https://github.com/rivine/recordchain/tree/master/api_spec

### Error 
```
/opt/code/github/rivine/recordchain_py# cd server/
/opt/code/github/rivine/recordchain_py/server# ls
Aci.capnp       bobject_api.py                    EnumSpecialType.capnp  index.html         server.py
aci.py          Bobject.capnp                     EnumSpecialType.py     LinkBobject.capnp  Special.capnp
acl_api.py      bobject.py                        Fileblock.capnp        link_bobject.py    special.py
Acl.capnp       client_support.py                 fileblock.py           Link.capnp         start_server.sh
acl.py          dir_api.py                        File.capnp             link.py            user_api.py
apidocs         Dir.capnp                         file.py                Posix.capnp        User.capnp
api_spec        dir.py                            generate_reset.sh      posix.py           user.py
app.py          EnumBobjectCompressionType.capnp  generate.sh            __pycache__
bdomain_api.py  EnumBobjectCompression_type.py    group_api.py           readme.md
Bdomain.capnp   EnumLinkType.capnp                Group.capnp            requirements.txt
bdomain.py      EnumLinkType.py                   group.py               schema
root@ahmedheaven:/opt/code/github/rivine/recordchain_py/server# ./start_server.sh 
./start_server.sh: line 1: cd: server: No such file or directory
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from acl_api import acl_api
  File "/opt/code/github/rivine/recordchain_py/server/acl_api.py", line 10, in <module>
    Acl_schema = JSON.load(open(dir_path + '/schema/Acl_schema.json'))
FileNotFoundError: [Errno 2] No such file or directory: '/opt/code/github/rivine/recordchain_py/server/schema/Acl_schema.json'

```

### Steps to reproduce: 
* `js9_code get --url "https://github.com/rivine/recordchain"`
* `js9_code get --url "https://github.com/rivine/recordchain_py"`
* generate ` go-raml server -l python --kind gevent-flask --ramlfile server/api_spec/main.raml --dir server`
* start
 ```
# ./start_server.sh 
./start_server.sh: line 1: cd: server: No such file or directory
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from acl_api import acl_api
  File "/opt/code/github/rivine/recordchain_py/server/acl_api.py", line 10, in <module>
    Acl_schema = JSON.load(open(dir_path + '/schema/Acl_schema.json'))
FileNotFoundError: [Errno 2] No such file or directory: '/opt/code/github/rivine/recordchain_py/server/schema/Acl_schema.json'

```

So it searches for Acl_schema.json
```ls schema/
aci_schema.json      dir_schema.json        link_bobject_schema.json  List_Bobject_schema.json  posix_schema.json
acl_schema.json      fileblock_schema.json  link_schema.json          List_Dir_schema.json      special_schema.json
bdomain_schema.json  file_schema.json       List_Acl_schema.json      List_Group_schema.json    user_schema.json
bobject_schema.json  group_schema.json      List_Bdomain_schema.json  List_User_schema.json
```
and the generated one is lowercase `acl_schema.json`

**Comment by iwanbk** [comment]
can you provide the .raml?

**Comment by xmonader** [comment]
@iwanbk, Sorry! I updated the issue with link to API specs. https://github.com/rivine/recordchain/tree/master/api_spec

**Comment by iwanbk** [comment]
I think the bug is in the .raml side

https://github.com/rivine/recordchain/blob/efebf04deb8b07c7d58414f27bcb929ef85565c6/api_spec/resourcetypes.raml#L63-L64

```
 <<resourcePathName | !singularize | !uppercamelcase>>
``` 

means that request body use Upper camel case, it converts `acl` to `Acl`.
while there is only `acl` in the `types` section

**Comment by xmonader** [comment]
You're totally right. please feel free to close this issue :)
